FROM nvidia/cuda:11.8.0-base-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
# Install other requirements excluding torch
RUN grep -v 'torch' requirements.txt > temp_requirements.txt
RUN pip3 install --no-cache-dir -r temp_requirements.txt && rm temp_requirements.txt

# Install PyTorch with CUDA support
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118

COPY . .
ENV PYTHONPATH=/app:$PYTHONPATH

CMD ["python3", "run.py"]
