services:
  backend:
    container_name: whisper-transcript
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ${GPU_DOCKERFILE:-Dockerfile.cpu}
    ports:
      - "5000:5000"
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - FLASK_APP=${FLASK_APP:-app}
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
    volumes:
      - .:/app
    group_add:
      - ${GPU_GROUP:-video}
    cap_add:
      - SYS_PTRACE
